# Generated by Django 5.2.1 on 2025-06-02 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Locataire',
            fields=[
                ('code', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('cni', models.CharField(max_length=30)),
                ('nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50)),
                ('telephone', models.CharField(max_length=30)),
                ('adresse', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Proprietaire',
            fields=[
                ('code', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('cni', models.CharField(max_length=30)),
                ('nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50)),
                ('telephone', models.CharField(max_length=30)),
                ('adresse', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Logement',
            fields=[
                ('id_logement', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('adresse', models.CharField(max_length=30)),
                ('ville', models.CharField(max_length=30)),
                ('type_logement', models.CharField(max_length=30)),
                ('nombre_piece', models.IntegerField()),
                ('statut', models.CharField(max_length=30)),
                ('locataire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.locataire')),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.proprietaire')),
            ],
        ),
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('id_contrat', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('type_contrat', models.CharField(max_length=30)),
                ('locataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.locataire')),
                ('logement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.logement')),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.proprietaire')),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('ref', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('date_paiement', models.DateField()),
                ('montant', models.IntegerField()),
                ('moyen_paiement', models.CharField(max_length=30)),
                ('contrat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.contrat')),
                ('logement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.logement')),
            ],
        ),
    ]
